In [ ]:
import retro
import pygame
import numpy as np
import gzip
import os
#importing the optmizations frame
import optuna 
#PPO for RL
from stable_baselines3 import PPO
#Bringing the eval policy method for metric calculation
from stable_baselines3.common.evaluation import evaluate_policy
#importing the sb3 monitor for loggin
from stable_baselines3.common.monitor import Monitor
#importing the vec wrappers to vectorize  and frame stack
from stable_baselines3.common.vec_env import DummyVecEnv, VecFrameStack 
import os 


: 

In [ ]:
model = PPO.load('./train_zigs/best_model_80000_zigzag.zip')

In [ ]:
mean_reward, _ = evaluate_policy(model,env,render = True , n_eval_episodes= 5 )

In [1]:
import retro
import pygame
import numpy as np
import gzip
import os

def main():
    pygame.init()
    screen = pygame.display.set_mode((640, 480))
    pygame.display.set_caption("Jogue Sonic manualmente com teclado")

    env = retro.make(game='SonicAndKnuckles3-Genesis')
    obs = env.reset()

    buttons = env.buttons
    print("Botões disponíveis no ambiente:", buttons)

    clock = pygame.time.Clock()

    save_path = r"C:\Users\danie\manual_save.state"

    while True:
        action = np.array([0] * len(buttons), dtype=np.bool_)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                env.close()
                pygame.quit()
                return

        keys = pygame.key.get_pressed()

        # Movimento com setas
        if keys[pygame.K_UP]:
            action[buttons.index('UP')] = 1
        if keys[pygame.K_DOWN]:
            action[buttons.index('DOWN')] = 1
        if keys[pygame.K_LEFT]:
            action[buttons.index('LEFT')] = 1
        if keys[pygame.K_RIGHT]:
            action[buttons.index('RIGHT')] = 1

        # Pular com Z (botão A)
        if keys[pygame.K_z]:
            action[buttons.index('A')] = 1

        # Botão B com Shift
        if keys[pygame.K_LSHIFT] or keys[pygame.K_RSHIFT]:
            action[buttons.index('B')] = 1

        # START com Enter
        if keys[pygame.K_RETURN]:
            action[buttons.index('START')] = 1

        obs, reward, done, info = env.step(action)
        env.render()

        # Salvar estado com S
        if keys[pygame.K_s]:
            content = env.em.get_state()
            with gzip.open(save_path, "wb") as f:
                f.write(content)
            print(f"Estado salvo em {save_path}")

        # Carregar estado com L
        if keys[pygame.K_l]:
            if os.path.exists(save_path):
                with gzip.open(save_path, "rb") as f:
                    content = f.read()
                env.em.set_state(content)
                print(f"Estado carregado de {save_path}")
            else:
                print("Arquivo de state não encontrado. Salve antes de carregar.")

        if done:
            print("Fase terminada, reiniciando...")
            obs = env.reset()

        clock.tick(60)

if __name__ == "__main__":
    main()


pygame 2.6.1 (SDL 2.28.4, Python 3.8.20)
Hello from the pygame community. https://www.pygame.org/contribute.html
Botões disponíveis no ambiente: ['B', 'A', 'MODE', 'START', 'UP', 'DOWN', 'LEFT', 'RIGHT', 'C', 'Y', 'X', 'Z']


c:\Users\danie\miniconda3\envs\project_sonic\lib\site-packages\pyglet\libs\win32\__init__.py:318: UserWarning: Could not set COM MTA mode. Unexpected behavior may occur.
  warnings.warn("Could not set COM MTA mode. Unexpected behavior may occur.")


Estado salvo em C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state
Estado carregado de C:\Users\danie\manual_save.state


KeyboardInterrupt: 

: 

In [1]:
import retro
print(retro.data.list_games())
print(retro.data.list_states('SonicAndKnuckles3-Genesis'))

['1942-Nes', '1943-Nes', '3NinjasKickBack-Genesis', '8Eyes-Nes', 'AaahhRealMonsters-Genesis', 'AbadoxTheDeadlyInnerWar-Nes', 'AcceleBrid-Snes', 'ActRaiser2-Snes', 'ActionPachio-Snes', 'AddamsFamily-GameBoy', 'AddamsFamily-Genesis', 'AddamsFamily-Nes', 'AddamsFamily-Sms', 'AddamsFamily-Snes', 'AddamsFamilyPugsleysScavengerHunt-Nes', 'AddamsFamilyPugsleysScavengerHunt-Snes', 'AdvancedBusterhawkGleylancer-Genesis', 'Adventure-Atari2600', 'AdventureIsland-GameBoy', 'AdventureIsland3-Nes', 'AdventureIslandII-Nes', 'AdventuresOfBatmanAndRobin-Genesis', 'AdventuresOfBayouBilly-Nes', 'AdventuresOfDinoRiki-Nes', 'AdventuresOfDrFranken-Snes', 'AdventuresOfKidKleets-Snes', 'AdventuresOfMightyMax-Genesis', 'AdventuresOfMightyMax-Snes', 'AdventuresOfRockyAndBullwinkleAndFriends-Genesis', 'AdventuresOfRockyAndBullwinkleAndFriends-Nes', 'AdventuresOfRockyAndBullwinkleAndFriends-Snes', 'AdventuresOfStarSaver-GameBoy', 'AdventuresOfYogiBear-Snes', 'AeroFighters-Snes', 'AeroStar-GameBoy', 'AeroTheAcroBa

In [3]:
#importing the optmizations frame
import optuna 
#PPO for RL
from stable_baselines3 import PPO
#Bringing the eval policy method for metric calculation
from stable_baselines3.common.evaluation import evaluate_policy
#importing the sb3 monitor for loggin
from stable_baselines3.common.monitor import Monitor
#importing the vec wrappers to vectorize  and frame stack
from stable_baselines3.common.vec_env import DummyVecEnv, VecFrameStack 
import os 

c:\Users\danie\miniconda3\envs\project_sonic\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
model = PPO.load('./train_zigs/best_model_13030000_zigzag')

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import time
from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.vec_env import DummyVecEnv, VecFrameStack # Import VecFrameStack
from gym import Env
from gym.spaces import Discrete, Box
import retro

# --- Sua classe Sonic (certifique-se de que esteja completa e funcional) ---
# ... (Sua classe Sonic aqui, igual à versão anterior) ...
BUTTONS = ['B', 'A', 'MODE', 'START', 'UP', 'DOWN', 'LEFT', 'RIGHT', 'C', 'Y', 'X', 'Z']

class Sonic(Env):
    def __init__(self):
        super().__init__()
        self.actions = [
            [],                      # Nada (0)
            ['RIGHT'],               # Andar para frente (1)
            ['LEFT'],                # Voltar (2)
            ['A'],                   # Pular (3)
            ['RIGHT', 'A'],          # Andar + Pular (4)
            ['DOWN'],                # Agachar (5)
            ['DOWN', 'A'],           # Spindash (6)
            ['LEFT', 'A'],           # Voltar + Pular (7)
        ]
        self._actions = []
        for combo in self.actions:
            arr = np.array([False] * len(BUTTONS))
            for btn in combo:
                arr[BUTTONS.index(btn)] = True
            self._actions.append(arr)
        self.action_space = Discrete(len(self._actions))
        
        # O espaço de observação aqui ainda é o de um único frame preprocessado (84, 84, 1)
        self.observation_space = Box(low=0, high=255, shape=(84, 84, 1), dtype=np.uint8)
        
        self.game = retro.make(game='SonicAndKnuckles3-Genesis', use_restricted_actions=retro.Actions.FILTERED)
        cv2.namedWindow("Sonic", cv2.WINDOW_NORMAL)
        cv2.resizeWindow("Sonic", 960, 672) 

    def step(self, action_index):
        real_moves = self._actions[action_index]
        obs, _, done, info = self.game.step(real_moves)
        obs_processed = self.preprocess(obs)
        frame_delta = (obs_processed - self.previous_frame) * 100
        self.previous_frame = obs_processed

        v = info['x'] - self.x
        c = -0.01
        d = -5 if info['lives'] < self.lives else 0
        reward = v * 0.01 + c + d

        delta_rings = info['rings'] - self.rings
        if delta_rings > 0:
            reward += delta_rings * 0.01
        elif delta_rings < 0:
            reward -= abs(delta_rings) * 0.01

        delta_score = info['score'] - self.score
        reward += delta_score * 0.0005
        reward += info.get('level_end_bonus', 0) * 0.0005

        delta_x = info['x'] - self.x
        if delta_x > 0:
            self.stuck_steps = 0
        else:
            self.stuck_steps += 1

        if self.stuck_steps >= 900:
            reward -= 0.2

        if self.stuck_steps >= 1200:
            done = True

        self.x = info['x']
        self.rings = info['rings']
        self.score = info['score']
        self.lives = info['lives']
        
        return obs_processed, reward, done, info

    def render(self, *args, **kwargs):
        frame = self.game.get_screen()
        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR) 
        scale_factor = 3
        new_width = int(frame.shape[1] * scale_factor)
        new_height = int(frame.shape[0] * scale_factor)
        display_frame = cv2.resize(frame, (new_width, new_height), interpolation=cv2.INTER_NEAREST)
        cv2.imshow("Sonic", display_frame)
        cv2.waitKey(1)

    def reset(self, *, seed=None, options=None):
        obs_raw = self.game.reset()
        obs_processed = self.preprocess(obs_raw)
        self.previous_frame = obs_processed
        self.lives = 3
        self.x = 0 
        self.rings = 0
        self.score = 0 
        self.stuck_steps = 0
        self.delta_max_x = 0
        return obs_processed

    def preprocess(self, observation):
        gray = cv2.cvtColor(observation, cv2.COLOR_RGB2GRAY) 
        resize = cv2.resize(gray, (84, 84), interpolation=cv2.INTER_CUBIC)
        channels = np.reshape(resize, (84, 84, 1))
        return channels
    
    def close(self):
        self.game.close()
        cv2.destroyAllWindows()


# --- Configuração do Ambiente e Carregamento do Modelo ---

# A função make_env_for_sb3 deve retornar um ambiente Gym básico
# que será então encapsulado por DummyVecEnv e VecFrameStack.
def make_initial_env():
    env = Sonic()
    # Adicione aqui StickyActionWrapper se você usou ele no TREINAMENTO,
    # antes do DummyVecEnv e VecFrameStack
    # Ex: env = StickyActionWrapper(env, repeat=4)
    return env

# Crie o ambiente vetorizado que será passado para o modelo.
# Ordem CORRETA:
# 1. DummyVecEnv: Transforma seu ambiente Sonic (não vetorizado) em um ambiente vetorizado (com num_envs=1).
# 2. VecFrameStack: Empilha frames *deste* ambiente vetorizado.

eval_env = DummyVecEnv([lambda: make_initial_env()])
eval_env = VecFrameStack(eval_env, 4, channels_order='first') # Usando 'first' baseado no erro (4, 84, 84)


# Carregue o modelo treinado
model_path = './train_zigs/best_model_13030000_zigzag.zip'
try:
    # Passe o ambiente vetorizado e com VecFrameStack para o modelo
    model = PPO.load(model_path, env=eval_env) 
    print(f"Modelo carregado com sucesso de {model_path}")
except Exception as e:
    print(f"Erro ao carregar o modelo: {e}")
    print("Verifique se o arquivo do modelo existe no caminho especificado e é compatível com o ambiente.")
    exit()

# --- Avaliação Usando evaluate_policy ---
num_evaluation_episodes = 5 

print(f"\n--- Iniciando avaliação com evaluate_policy para {num_evaluation_episodes} episódios ---")

# evaluate_policy usará eval_env que já está com VecFrameStack
mean_reward, std_reward = evaluate_policy(model, eval_env, n_eval_episodes=num_evaluation_episodes, render=True)

print(f"\nAvaliação Concluída:")
print(f"Recompensa Média ao longo de {num_evaluation_episodes} episódios: {mean_reward:.2f} +/- {std_reward:.2f}")

# Fechar o ambiente após a avaliação
eval_env.close()


# --- Para Plotar o Gráfico de Recompensa por Passo de um Único Episódio ---
print("\n--- Rodando um episódio adicional para visualizar o gráfico de recompensa por passo ---")

# Para este loop, você precisa de uma NOVA instância do ambiente COMPLETA,
# que inclua o DummyVecEnv e o VecFrameStack, assim como o `eval_env`.
# A maneira mais fácil é criar uma nova função lambda e passar para DummyVecEnv novamente.
single_episode_raw_env = make_initial_env() # Cria a base do ambiente
single_episode_vec_env = DummyVecEnv([lambda: single_episode_raw_env]) # Vetoriza
single_episode_env = VecFrameStack(single_episode_vec_env, 4, channels_order='first') # Aplica FrameStack


obs = single_episode_env.reset()
# 'obs' agora virá com a forma (num_envs, num_frames, height, width) = (1, 4, 84, 84)
# como esperado pelo modelo.

done = False
episode_reward_single = 0
rewards_history_single = []
current_steps_single = 0

MAX_STEPS_PER_EPISODE_SINGLE = 4500 

while not done and current_steps_single < MAX_STEPS_PER_EPISODE_SINGLE:
    single_episode_env.render()

    # obs já está no formato (1, 4, 84, 84) por causa do DummyVecEnv e VecFrameStack
    # Não precisa mais de np.expand_dims(obs, axis=0)
    action_index, _states = model.predict(obs, deterministic=True)
    
    # action_index virá como um array numpy de shape (1,)
    # obs, reward, done, info do VecEnv step são arrays, mesmo para num_envs=1
    obs, reward, done, info = single_episode_env.step(action_index) # Não use .item() aqui ainda
    
    # reward, done, info de um VecEnv são arrays de tamanho num_envs.
    # Para um único ambiente, pegue o primeiro elemento:
    episode_reward_single += reward[0] # Pegue a recompensa do primeiro (e único) ambiente
    rewards_history_single.append(reward[0])
    current_steps_single += 1
    # time.sleep(0.001)

    if done[0] or current_steps_single >= MAX_STEPS_PER_EPISODE_SINGLE: # Verifique done[0]
        if current_steps_single >= MAX_STEPS_PER_EPISODE_SINGLE and not done[0]:
            print(f"Visualisation episode finished: Limite de tempo (5 minutos) atingido!")
        else:
            print(f"Visualisation episode finished: Condição de fim de jogo atingida.")
        
        print(f"Total Reward for visualisation episode: {episode_reward_single:.2f}")
        print(f"Info for visualisation episode: {info[0]}") # Pegue info do primeiro ambiente
        
        plt.figure(figsize=(10, 5))
        plt.plot(rewards_history_single)
        plt.title(f'Recompensa por Passo (Modelo Treinado) - Episódio de Visualização (Total: {episode_reward_single:.2f}, Passos: {current_steps_single})')
        plt.xlabel('Passo no Episódio')
        plt.ylabel('Recompensa')
        plt.grid(True)
        plt.show()

single_episode_env.close() # Feche o ambiente vetorizado
print("\nSingle episode visualisation completed.")

Wrapping the env in a VecTransposeImage.
Erro ao carregar o modelo: Observation spaces do not match: Box([[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]], [[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 .

c:\Users\danie\miniconda3\envs\project_sonic\lib\site-packages\stable_baselines3\common\evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


ValueError: Error: Unexpected observation shape (1, 336, 84, 1) for Box environment, please use (4, 84, 84) or (n_env, 4, 84, 84) for the observation shape.

: 